### ISSUE TITLE
rancher - rke

### ISSUE THREAD

**Issue by GunSik2** [GunSik2/engineering_qna#13]
- Env: CentOS Linux release 7.7.1908
- Prepare Target OS
```
curl https://releases.rancher.com/install-docker/18.09.2.sh | sh
sudo usermod -aG docker your-user

LIP=10.0.5.78
iptables -A INPUT -p tcp --dport 6443 -j ACCEPT
iptables -A INPUT -p tcp -s $LIP --dport 6443 -j ACCEPT

firewall-cmd --zone=public --add-port=6443/tcp --permanent
firewall-cmd --reload
firewall-cmd --permanent --zone=public --add-rich-rule="
  rule family='ipv4'
  source address=\"$LIP/32\"
  port protocol='tcp' port='6443' accept"
firewall-cmd --reload

cat /etc/ssh/sshd_config | grep AllowTcpForwarding
AllowTcpForwarding yes
```
- Installation
```
wget https://github.com/rancher/rke/releases/download/v1.0.7-rc2/rke_linux-amd64
chmod +x rke

rke --version
```
- cluster.yml
```
nodes:
    - address: 10.0.5.78
      user: centos
      role:
        - controlplane
        - etcd
        - worker
```
- deploy 
```
rke up
```

- Reference
  - https://rancher.com/docs/rke/latest/en/installation/
  - https://rancher.com/docs/rke/latest/en/os/
  - #12
